# Generated by Django 5.2.4 on 2025-08-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deck_data',
        ),
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(default='null', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('power', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('height', models.CharField(max_length=50)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.deck')),
            ],
            options={
                'ordering': ['deck', 'rank'],
                'unique_together': {('deck', 'rank')},
            },
        ),
    ]
