# Generated by Django 5.2.4 on 2025-08-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_deck_deck_data_deck_name_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['deck', 'Rank']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='height',
            new_name='Height',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='intelligence',
            new_name='Intelligence',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='power',
            new_name='Power',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='rank',
            new_name='Rank',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='speed',
            new_name='Speed',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='strength',
            new_name='Strength',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('deck', 'Rank')},
        ),
    ]
