# Generated by Django 5.2.4 on 2025-08-21 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_card_options_rename_height_card_height_and_more'),
        ('web', '0008_remove_player_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players_in_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_given_to_each_player', models.TextField(default='[]')),
                ('Cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('Players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.gamesession')),
            ],
        ),
    ]
