# Generated by Django 5.2.4 on 2025-08-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_players_in_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players_in_game',
        ),
    ]
