# Generated by Django 5.2.4 on 2025-08-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='Name',
            new_name='name',
        ),
    ]
