# Generated by Django 5.2.4 on 2025-08-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Rank', models.CharField(max_length=20)),
                ('No_of_matches_played', models.IntegerField()),
                ('No_of_matches_won', models.IntegerField()),
                ('winning_streak', models.IntegerField()),
                ('No_of_achievements', models.IntegerField()),
            ],
        ),
    ]
