# Generated by Django 5.2.4 on 2025-08-04 14:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='pfp.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(blank=True, max_length=20, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='player',
            name='No_of_achievements',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='No_of_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='No_of_matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='Rank',
            field=models.CharField(default='NOOB', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='winning_streak',
            field=models.IntegerField(default=0),
        ),
    ]
