# Generated by Django 5.2.4 on 2025-08-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_gamesession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(blank=True, default='player', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='assets/pfp.png', upload_to=''),
        ),
    ]
