# Generated by Django 5.2.4 on 2025-08-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_player_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
    ]
